### ISSUE TITLE
Type de coût dans la liste des charges

### ISSUE THREAD

**Issue by bv74** [Darkjeff/ultimateimmo#104]
Bonjour, 

dans la liste des charges, ou la fiche d'une charge, le type de coût est remplacé par la lettre M. Lorsqu'on passe en modification, c'est la valeur saisie qui apparait, ce qui est correct. 
cdlt. 
B

**Comment by mikygee** [comment]
Bonjour,
Pourrais-tu faire une capture écran, car de mon côté, mis à part le M parasite j'ai bien le type de charge qui s'affiche.
![image](https://user-images.githubusercontent.com/2222550/189257116-af368ede-c385-4837-a834-95ac5a2ebe2f.png)

**Comment by bv74** [comment]
Bonjour, 
voici la copie. C'est dans la fiche des charge. 
![2022](https://user-images.githubusercontent.com/43907350/189286208-3aaed881-1a20-4e43-acda-4ffe8fa78d5b.png)

et dans la liste : 

![2022-1](https://user-images.githubusercontent.com/43907350/189286579-bbdf5b78-5367-4d0e-93d2-21fd8ce3eeda.png)
Je n'ai pas la dernière version de ultimate immo, mais toutefois c'est récent. 
bonne journée.

**Comment by mikygee** [comment]
Le mieux serait de bien vérifier que tu ais la dernière version.
Regarde si lorsque tu essaies de cloner un bien tu as un accent circonflexe sur le Êtes de "Êtes vous sûr de vouloir cloner le bien" c'est l'un des derniers changements que j'ai poussé.

**Comment by bv74** [comment]
bonjour @mikygee 
oui j'ai bien le dit accent circonflexe : 
![Capture d’écran du 2022-09-10 08-02-18](https://user-images.githubusercontent.com/43907350/189471431-aa855372-f99b-43c8-906e-179909e75924.png)

**Comment by bv74** [comment]
Bonjour, 
je viens de mettre à jour avec la dernière version disponible sur github : [96dfc20]. J'ai toujours la lettre M pour les types de coûts tant dans la liste que sur la fiche sauf lorsque j'édite. 
cdlt.B

**Comment by bv74** [comment]
problème résolu
