### ISSUE TITLE
Bug : message d'erreur à l'affichage de la page liste des propriétaires

### ISSUE THREAD

**Issue by bv74** [Darkjeff/ultimateimmo#110]
Bonjour, 

lors de l'affichage de la page des propriétaires 
`ultimateimmo/owner/immoowner_list.php?idmenu=700&mainmenu=properties&leftmenu=`
j'ai le message suivant : missing configuration typeCostForAdjust. 
![image](https://user-images.githubusercontent.com/43907350/193815477-601fd027-144e-4877-b5cc-aebbecc7f146.png)

Comment comprendre ce message ? 
cdlt.
B

**Comment by Darkjeff** [comment]
une valeur a réglé dans la config du module (le rowid du type de charge qui correspond au charges commune )

Dans quittances et baux

**Comment by bv74** [comment]
9a semble être réglé. Merci @Darkjeff
