### ISSUE TITLE
Bug: Nom/Prénom du locataire affichée au lieu de sa référence

### ISSUE THREAD

**Issue by mikygee** [Darkjeff/ultimateimmo#114]
Version du module ultimateimmo du 10/10/2022.

Bonjour,

Dans la colonne référence du locataire c'est son nom/prénom qui est affiché au lieu de sa référence.
![image](https://user-images.githubusercontent.com/2222550/194850206-33d9eb28-966d-487d-8d46-4c5efde13b6b.png)

Alors que la référence indiquée dans ma fiche locataire est celle-ci
![image](https://user-images.githubusercontent.com/2222550/194850388-62cd240f-13e3-4371-8d46-cedc1580e52a.png)

Cdt

**Comment by FHenry** [comment]
La recherche fonctionne sur nom et prenom, la ref=id aprés la création, inutile de conserver la ref (prov) dans le cas d'un locataire
