### ISSUE TITLE
Anomalie : création nouvelle charge

### ISSUE THREAD

**Issue by bv74** [Darkjeff/ultimateimmo#116]
Bonjour, 
j'ai le message d'erreur lors de la création d'une nouvelle charge avec la version  [3ed3106](https://github.com/Darkjeff/ultimateimmo/commit/3ed3106547c43dd55667b0b84c08721374b5a3f5): 
Column 'fk_user_create' cannot be null

bien cdlt.

**Comment by mikygee** [comment]
Bonjour,
Pourrais-tu me passer la commande suivante.
DESC llx_ultimateimmo_immocost;
Je vais tester le sujet que tu remontes ce soir.

**Comment by bv74** [comment]
Bonjour, 
j'ai récupéré la version [9c05b70](https://github.com/Darkjeff/ultimateimmo/commit/9c05b7062c83cbdde37b4015e8c0aca60814b9ac) et j'ai appliqué la requête SQL. J'ai le même message : Column 'fk_user_create' cannot be null
cdlt.

**Comment by mikygee** [comment]
Pourrais-tu me passer la commande suivante.
DESC llx_ultimateimmo_immocost;
