### ISSUE TITLE
Bug: Page de statistiques de compteurs incohérente lorsqu'on filtre sur le type de compteurs

### ISSUE THREAD

**Issue by mikygee** [Darkjeff/ultimateimmo#124]
Bonjour,

Les calculs sont complètements faussés lorsqu'on filtre sur un compteur en particulier sur la page compteur/stats.php
![image](https://user-images.githubusercontent.com/2222550/195823625-b7f56e9c-1302-4239-a2f7-a14cca28531a.png)

Sans le filtre j'ai ça, et ça m'a l'air cohérent.
![image](https://user-images.githubusercontent.com/2222550/195823838-2539da91-689d-40bb-881a-06d2fa6aeb5a.png)

**Comment by Darkjeff** [comment]
faut filtrer par immeuble + type de compteur (et là normalement ça fonctionne)

**Comment by FHenry** [comment]
le filtre par type est maintenant obligatoire
