### ISSUE TITLE
Anomalie : pas de bouton pour enregistrer modification propriétaire

### ISSUE THREAD

**Issue by bv74** [Darkjeff/ultimateimmo#125]
Bonjour, 

lorsque je modifie un propriétaire, je ne trouve pas de bouton « valider ».
htdocs/custom/ultimateimmo/owner/immoowner_card.php?id=1
cdlt.

**Comment by mikygee** [comment]
Bonjour,
Ca serait super si tu pouvais mettre des captures écran (en général)

**Comment by bv74** [comment]
Bonjour @mikygee, 
est-ce mieux ainsi ?
Je pensais avoir un bouton de validation ou d'enregistrement au bas de cette page : 
![2022-10-14_16-55](https://user-images.githubusercontent.com/43907350/195877787-472deff7-2553-44ca-9679-59dbfedf50a2.png)

**Comment by Darkjeff** [comment]
j'ai bien le bouton créer et annuler sur propriétaire 

tu es bien en dolibarr V15 ?

**Comment by bv74** [comment]
Je suis en Dolibar 14.0.5.
Je vais migrer en 15, ce WE si je suis courageux ;-)

**Comment by bv74** [comment]
C'est fonctionnel en v15
