### ISSUE TITLE
Traduction page acceuil

### ISSUE THREAD

**Issue by bv74** [Darkjeff/ultimateimmo#130]
Bonjour, 

le menu d'accueil [htdocs/custom/ultimateimmo/dashboard.php?idmenu=931&mainmenu=properties&leftmenu=](url) mène à une page non traduite : 
![image](https://user-images.githubusercontent.com/43907350/210957073-acb27f32-deb5-4268-a18e-f130f9902ddd.png)

**Comment by mikygee** [comment]
Bonjour,
J'ai proposé une action corrective pour la traduction. A valider.
