### ISSUE TITLE
Numero EDF PRM, PDL

### ISSUE THREAD

**Issue by bv74** [Darkjeff/ultimateimmo#132]
Bonjour, 

une amélioration : est-il possilbe d'ajouter un champ je pense dans la fiche du bien immobilier pour saisir le numéro PRM/PDL de EDF. 
Pour le gaz, télécom et l'eau je ne sais pas comment cela fonctionne. Mais peut être faire la même chose avec ces réseaux.

**Comment by mikygee** [comment]
Bonjour,
Tout à fait, on pourrait aussi ajouter le numéro de téléphone de la ligne Internet.
Souvent à l'arrivée d'un nouveau locataire, il y a besoin de connaitre le numéro de l'ancienne ligne pour réactiver l'accès Internet.
Peut être faudrait-il mettre ces informations dans un onglet spécifique, mais à ce jour il est possible de les mettre dans les notes en solution de contournement.
Cdt

**Comment by Darkjeff** [comment]
c'est ajouté ^^

![image](https://user-images.githubusercontent.com/1095260/211596878-0a2e49a7-2979-4b18-972a-37af7d0216b2.png)
