### ISSUE TITLE
Table '.doli_c_ultimateimmo_immoreceipt_status' doesn't exist

### ISSUE THREAD

**Issue by Allread** [Darkjeff/ultimateimmo#133]
Bonjour 👍 
J'ai téléchargé le module pour une mise en ligne sur Dolibarr 17.0.0
Mais lors de l'activation du module, j'ai une erreur "Table 'xxxxx.doli_c_ultimateimmo_immoreceipt_status' doesn't exist"

J'ai mis le module dans /custom/ et l'ai nommé ultimateimmo-15.0.0

**Comment by Darkjeff** [comment]
j'ai pas encore testé sur un doli 17

mais le répertoire dans custom doit se nommer ultimateimmo

**Comment by Allread** [comment]
Ahhh merci @Darkjeff :) Ca fonctionne beaucoup mieux :) Si j'y pense, je ferais un back sur la v17.0.0
