### ISSUE TITLE
Error forging a SQL request from an universal criteria: Bad syntax of the search string, filter criteria is inhalited

### ISSUE THREAD

**Issue by Allread** [Darkjeff/ultimateimmo#134]
Lors de la création d'un nouveau proprietaire, d'un nouveau locataire ou d'un nouveau bien, nous avons des Erreur SQL

![image](https://user-images.githubusercontent.com/16807391/236396422-e9c020ee-b712-437a-a900-f8bb116ce791.png)

![image](https://user-images.githubusercontent.com/16807391/236396484-7cbbfe04-e97f-4067-a5c6-7b14b474559c.png)

Version Dolibarr : 17.0.0

**Comment by mikewiza** [comment]
Bonjour

Perso je n'utilise pas la version 17 mais on parle de votre soucis ici. 
[https://www.dolibarr.fr/forum/t/erreur-nomenclature-par-defaut-error-forging-a-sql-request-from-an-universal-criteria-bad-syntax-of-the-search-string-filter-criteria-is-inhalited/42716](url)

A votre place je ferai un update car la version 17.0.1 corrige ce problème.

**Comment by malyckool** [comment]
Bonjour,
Même problème constaté avec la version  17.01 de Dolibarr.

**Comment by FHenry** [comment]
Corrigé
