### ISSUE TITLE
Toutes les créations sont impossibles -> écran blanc (dolibarr 19.02 & 20.0.0 ; php8.2 ; mariadb 15.1 ; debian bookworm)

### ISSUE THREAD

**Issue by g-vidal** [Darkjeff/ultimateimmo#141]
Bonjour,
(la liste semble bilingue je me permets le français)

**Ma config :**
* `linux ######## 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64 GNU/Linux`
* PHP 8.2.24 (cli) (built: Sep 27 2024 04:16:10) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.24, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.24, Copyright (c), by Zend Technologies
* nginx version: nginx/1.22.1
* ultimateimmo du master construit par ./ci.sh -> module_ultimateimmo-15.0.0.zip

_Installation from scratch de Dolibarr et ajout de module_ultimateimmo-15.0.0.zip sans aucun problème.
Le bouton du module apparait dans la barre des menus après activation.
La page de garde du module s'ouvre avec un menu complet (?) et trois pavés pour ajouter des éléments._

Tout clic sur un pavé ou sur la ligne du menu conduit à  une page blanche sans erreur signalée.
Plus généralement tous les alinéas du menu envoient une page blanche hormis :

- répartition des charges avec erreur : Missing configuration TypeCostForAdjust
- coût locataire qui donne trois tableaux vides avec les noms de mois en en-tête
- nouvelle charge avec 2 pavés d'entrée actifs et rien en face de "bien immobilier"
- statistiques de paiement
- coût locataire
- statistiques de loyer
- compteur / coût
- nouveau compteur
- lots fidcaux
- nouveau type qui semble parfaitement complet (Réf, libellé, note privée, note publique, état)
- liste de types de propriétaires tableau fonctionnel (Réf, libellé,  état)

La barre de debug disparait et il n'est pas possible d'avoir de message
L'outil de dev web envoie une 500 sur :
https://climatetmeteo.org/custom/ultimateimmo/owner/immoowner_card.php?action=create&idmenu=47&mainmenu=properties&leftmenu=
et les pages *_card.php correspondantes des autres commandes)

Depuis la liste des types de biens qui fonctionne il est possible de cliquer sur le bouton `ajouter` qui renvoie une l'erreur suivante sur la page :
_ Dolibarr a détecté une erreur technique.
Ces informations peuvent être utiles à des fins de diagnostic (vous pouvez définir l'option $dolibarr_main_prod sur '1' pour masquer les informations sensibles):
Date: 20241012144543
Dolibarr: 19.0.2 - https://www.dolibarr.org
Niveau de fonctionnalités: 0
PHP: 8.2.24
Serveur: nginx/1.22.1
OS: Linux kiteserver 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0

Url sollicitée: /custom/ultimateimmo/dict.php?id=3
Referer: https://climatetmeteo.org/
Gestionnaire de menu: eldy_menu.php

_Modules/Applications: user, api, fournisseur, supplier_proposal, accounting, facture, banque, tax, import, prelevement, export, fckeditor, paymentbybanktransfer, service, projet, eventorganization, societe, categorie, resource, contrat, ecm, bookmark, ficheinter, workflow, ticket, opensurvey, website, agenda, socialnetworks, notification, mailing, emailcollector, cron, externalsite, gravatar, printing, dav, debugbar, ultimateimmo
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: INSERT INTO llx_c_ultimateimmo_immoproperty_type (rowid,code,label,active) VALUES(7,null,'Maison individuelle',1)
Code retour dernier accès en base en erreur: DB_ERROR_CONSTRAINT
Information sur le dernier accès en base en erreur: Column 'code' cannot be null_ 

Je ne suis pas développeur et je ne connais pas le PHP, je pux tester des modifs si cela peut aider.

**Comment by g-vidal** [comment]
Migration en 20.0.1 aucun changement.

**Comment by mikygee** [comment]
Bonjour,
Si je me réfère à la dernière erreur, il manque une colonne dans une table MariaDB.
Il y a un répertoire sql où il faut éventuellement utiliser pour créer de nouvelles colonnes.
Sinon, essayez de désactiver/réactiver le module.
Je testerai le module fin octobre cela fait un moment, que je ne l'ai pas retesté.
Cdt

**Comment by g-vidal** [comment]
Merci de cette réponse rapide, voici quelques précisions sur ce point précis. 
J'ai vérifié la base elle semble contenir toutes les colonnes nécessaires

MariaDB [dbDolibarr]> SHOW COLUMNS FROM llx_c_ultimateimmo_immoproperty_type;
+--------+--------------+------+-----+---------+----------------+
| Field  | Type         | Null | Key | Default | Extra          |
+--------+--------------+------+-----+---------+----------------+
| rowid  | int(11)      | NO   | PRI | NULL    | auto_increment |
| code   | varchar(50)  | NO   |     | NULL    |                |
| entity | int(11)      | NO   |     | 1       |                |
| label  | varchar(255) | YES  |     | NULL    |                |
| active | tinyint(4)   | NO   |     | 1       |                |
| module | varchar(32)  | YES  |     | NULL    |                |
+--------+--------------+------+-----+---------+----------------+

De ce que je comprends (?) la requette en voie le deuxième paramètre à 'NULL'  alors que c'est interdit me semble-t-il dans la base il n'y a pas de champ  code sur la page d'où on part 
`https://climatetmeteo.org/custom/ultimateimmo/dict.php?id=3,,è
et d'ailleurs si on essaie de modifier un type existant on a l'erreur :
`Column 'code' cannot be null`

j'ai trouvé le fichier update .sql dont une des commandes est  effectivement:
`ALTER TABLE llx_c_ultimateimmo_immoproperty_type MODIFY COLUMN code varchar(50) NOT NULL;`
et là aussi si je comprends bien (?) cela doit faire l'opération nécessaire.
Je vais tester et je ferai un retour.

**Comment by mikygee** [comment]
A la lecture du message j'ai l'impression que
`ALTER TABLE llx_c_ultimateimmo_immoproperty_type MODIFY COLUMN code varchar(50) NOT NULL;`
est déjà appliqué

Il est possible que code soit une clé primaire d'une autre table.
Je brainstorm en te répondant.

Mais si c'est le cas, et que code est utilisé en tant que clé primaire ailleurs, alors il ne faut pas modifier les tables mais plutôt regarder pourquoi code arrive en tant que valeur null au moment de l’exécution de la requête.

J'ai pas suivi le développement du module depuis début 2023.
J'ai travaillé sur le développement de ma SCI.

**Comment by g-vidal** [comment]
Effectivement le contenu de `update.sql` a été appliqué (au moins pour TOUS  les points que j'ai vérifiés) . Pour en avoir le cœur net j'ai appliqué `ALTER TABLE llx_c_ultimateimmo_immoproperty_type MODIFY COLUMN code varchar(50) NULL;` et j'ai obtenu le résultat escompté : l'erreur ci dessus disparait... Mais on n'est pas plus avancés car je ne trouve pas de moyen pour modifier l'élément ajouté (lui ajouter un code) ni même de le supprimer.

Je suis d'accord avec ta réflexion le problème vient probablement de ce que l'input de la requête (issu de l'interface web)  ne contient pas de valeur pour la variable `code` et envoie donc `NULL`. Cela me semble lié au fait que l'interface ne propose pas de champ pour entrer une valeur (si c'est un automatisme par incrémentation qui ne fonctionne pas je suis incompétent pour le trouver).
Je ne parviens pas non plus à trouver  comment avoir un log avec des messages d'erreur pour le bug des écrans blancs quand on veut créer un élément, la barre de debug disparait. Le fichier `dolibarr.log` en mode debug contient des requêtes qui semblent fonctionner convenablement (pour celles que j'ai exécutées sur la base que je crois correspondre à la demande de création d'un nouvel utilisateur).

Une question peut-être stupide mais sait-on jamais. Faut-il enlever le fichier install.lock de documents et re-rendre conf/conf.php inscriptible pour ajouter/activer le module ultimateimmo ???

Merci des réponses à la volée, je saurai patienter car  comme beaucoup d'autres copropriétés nous sommes confrontés à un syndic au mieux incompétent  et la mise en œuvre d'un logiciel au sein du conseil syndical ressemble vraiment à une planche de salut.

**Comment by homer8173** [comment]
Bonjour, je pense que vous en demandez beaucoup en utilisant php8.2
j'ai utilisé ce code avec php 8.1 et je n'ai pas eu d'écran blanc.

**Comment by g-vidal** [comment]
Bonjour, le 8.2 est la version PHP par défaut de ma bookworm j'ai fait une install par défaut comme je l'ai écrit plus haut, j'ai cherché dans les paquets une autre version et je ne trouve pas.
J'ai activé le module log et   fait quelques requêtes le log est attaché.
Je reste à votre disposition
[dolibarrLog.zip](https://github.com/user-attachments/files/17362848/dolibarrLog.zip)

**Comment by homer8173** [comment]
Bonjour,,
les package PHP se trouvent sur sury https://gist.github.com/Razuuu/f646c3be44c5ba3b9c8e38b0a856d7b4
Les logs de dolibarr c'est sympa mais les erreurs PHP ça me servira plus.
Bien à vous,

**Comment by g-vidal** [comment]
Désolé j'ai cru que Dolibarr  regroupait tous les logs en mode debug.  Voici en attaché le log de nginx
[phpDolibLog.zip](https://github.com/user-attachments/files/17370595/phpDolibLog.zip)

**Comment by mikygee** [comment]
Bonjour,
En tous cas le module ne fonctionne pas de mon côté (version Dolibarr 20.0.1)
J'ai beaucoup de warning, d'erreurs etc.
Pour moi, ce module n'est pas compatible avec les dernières versions de Dolibarr.
Il l'était avec les versions 15 et 16 quand je l'ai utilisé.

**Comment by g-vidal** [comment]
Bonjour et merci du temps consacré, 
EN 19.02  il ne fonctionne pas non plus. j'ai jeté un coup d’œil de béotien en PHP aux logs et j'ai l'impression qu'il y a quelques erreurs qui paraissent systémiques suite apparemment à un changement de paramètres  passés dans une fonction qui revient souvent.  Cela confirmerait qu'une modification  dans une montée de version a transgressé les règles de compatibilité  lors de la 18 ou de la 19.

**Comment by homer8173** [comment]
Chers membres de la communauté Ultimateimmo,
Nous avons pris en compte vos retours sur Ultimateimmo et avons travaillé intensivement pour corriger les bugs et garantir une compatibilité avec la dernière version de Dolibarr ainsi que PHP 8.2. Ces améliorations vont considérablement améliorer la stabilité et l’efficacité de l'outil.
Cependant, cette mise à jour nous a coûté environ 700€, sans compter le temps investi pour répondre à vos attentes. Afin de continuer à fournir des améliorations régulières, nous avons besoin de votre soutien.
Vous pouvez nous aider en devenant sponsor via le bouton dédié. Chaque contribution est précieuse et permettra de maintenir et d’améliorer encore Ultimateimmo.
Merci pour votre soutien et votre confiance !

**Comment by mikygee** [comment]
Bonjour Norbert,
Je pense qu'il faudrait pousser ce type de message sur le forum Dolibarr ou quelque part sur Github, mais il me semble que sur ce ticket nous sommes 3.
- Toi
- Gérard qui souhaite tester ce module
- Moi qui ne l'utilise pas (car à l'époque il ne répondait pas vraiment à mes besoins et mes appartements n'étaient pas en location) et j'ai passé des heures et des heures à pousser des fix concernant des bugs, un  peu plus d'une quarantaine de commits.
Bon week end

**Comment by homer8173** [comment]
Bonsoir @mikygee Soyons clair, je ne cherche pas à me faire rétribuer sur ma participation, mais plus à éduquer sur la vie des open sources et à faire vivre le code. Désolé si mon message n'en disait pas plus sur mes intentions. La participation n'est d'ailleurs pas en mon nom mais sur le fondateur. Le lien devrait fonctionner prochainement pour ceux qui peuvent aider financièrement. Bon week-end à tous

**Comment by g-vidal** [comment]
La question initiale a été résolue par le commit #142  à condition de respecter l'ajout des variables précisé dans le commentaire #144
