### ISSUE TITLE
Page blanche

### ISSUE THREAD

**Issue by bv74** [Darkjeff/ultimateimmo#44]
Bonjour, 

je viens de tester le code déposé il y a 6 jours. J'ai deux pages blanches : 
https://xxxx/ultimateimmo/htdocs/custom/ultimateimmo/receipt/immoreceipt_list.php?idmenu=401&mainmenu=immoreceipts&leftmenu=
https://xxxx/ultimateimmo/htdocs/custom/ultimateimmo/property/immoproperty_list.php?idmenu=378&mainmenu=properties&leftmenu=

les autres pages fonctionnent. Dans la version précédente (décembre de mémoire) je n'avais pas ces soucis. 

Cordialement. 
BVA

**Comment by Darkjeff** [comment]
Oui le passage sur une V14

prochaine grosse modif debut mars 
afin de récup une version stable en V14

merci pour les retours 

ça permet d'établir la todo ^^

**Comment by bv74** [comment]
Bonjour, 
merci pour le retour. Alors je vais passer sur une 14.0.5.
Cordialement. 
BVA

**Comment by mikygee** [comment]
Bonjour @bv74, avez-vous résolu votre problème ?

**Comment by bv74** [comment]
Bonjour @mikygee 
pour moi le Pb est résolu. Je suis avec Dolibarr 14.0.5 et j'ai la dernière version du module immobilier
cdlt

**Comment by mikygee** [comment]
Bonjour @bv74, je pense qu'il faudrait clôturer ce ticket si le problème est résolu.

**Comment by bv74** [comment]
Pb résolu avec les mises à jour
