### ISSUE TITLE
 Onglet Quittances Charges locatives restent vide #45 

### ISSUE THREAD

**Issue by mikewiza** [Darkjeff/ultimateimmo#49]
Il faut creer des batiment et des propriété (bien) qui sont dedans

_Originally posted by @FHenry in https://github.com/Darkjeff/immobilier/issues/45#issuecomment-1115938986_

**Comment by mikewiza** [comment]
Bonjour

Je ne suis pas sur de comprendre ce que vous voulez dire, j'ai bien une liste de biens 
![Biens](https://user-images.githubusercontent.com/93732926/166973997-2666554d-8656-489d-b82f-ddf07a89e72b.png)

Les charges locatives n'apparaissent pas. Si de votre côté ça fonctionne c'est je renseigne pas au bonne endroit. Pourriez vous m'aiguiller?

**Comment by Darkjeff** [comment]
Il faut un bien principal qui sera le bien parent si il y a plusieurs lots dans le bien 
![image](https://user-images.githubusercontent.com/1095260/167436623-ecf898a2-5000-48f5-a7bb-48c392e48bb7.png)

les charges se calculent par bien principaux


![image](https://user-images.githubusercontent.com/1095260/167436865-042aea4b-3d3b-4b87-ab98-02ae8146ee44.png)

**Comment by mikewiza** [comment]
Merci pour l'aide malheureusement ça ne fonctionne pas. Quand on crée un bien principal on obtient les messages suivant:
fk_owner, fk_user_creat, status ,property_type_id, ref ,date_creation  "doesn't have a default value". 
J'ai donc édité la table immoproperty et mis NULL dans la valeur par défaut ou la date
![Immoproperty_structure_table](https://user-images.githubusercontent.com/93732926/167683151-43bd6db9-ed40-44dc-bb4c-4b11ea3868a9.png)

Après j'ai pu créer un bien principal et l'associer à l'appartement
![Immeuble_C](https://user-images.githubusercontent.com/93732926/167683348-1e754609-14a7-403c-a29d-23dfebe4fde2.png)

J'ai créé des charges qui sont associées à l'immeuble
![Charges_locatives](https://user-images.githubusercontent.com/93732926/167683664-7e58c11a-bdc5-4add-8674-2e3415b9e2fa.png)

Mais ça ne fonctionne pas

![Charges_Type](https://user-images.githubusercontent.com/93732926/167683956-de8f7271-2296-4733-a749-0a214a93388c.png)
![résultats_statistiques](https://user-images.githubusercontent.com/93732926/167683962-ca5b4250-e7e1-4049-b1e7-d04ba9e393dc.png)

Ma méthode est elle correcte? La structure de la table modifiée est cohérente?
**Une petite precision il y a 2 appartements dans 2 immeubles différents donc 2 biens principaux.**

**Comment by Darkjeff** [comment]
je pense que le problème vient du fk_owner 
j'ai du mettre une exception si le fk_owner = 1 il voit tout 
sinon le propriétaire (fk_owner) ne voit que ses biens 

j'essaye de patcher ça dés que je peux

**Comment by mikewiza** [comment]
Bonjour

_stat loyer et paiement ça fonctionne tu vois les deux biens ?_

oui les 2 appartements apparaissent
![Stat_Loyer](https://user-images.githubusercontent.com/93732926/167899765-729dcfa1-de87-462d-9773-691da914359b.png)

J'attends avec impatience le patch merci (◠﹏◠)

**Comment by mikewiza** [comment]
Bonjour
Avez-vous pu travailler sur le sujet?
Je vois que FHenry a créé une branche 15.0( c'est la version de Dolibarr que j'utilise). Je me demande quelle branche utiliser car toutes les évolutions sont sur la branche Master?

**Comment by Darkjeff** [comment]
faut utiliser master

**Comment by mikewiza** [comment]
Le problème semble résolu. J'avais bien créer l'appartement et l'immeuble qui va avec mais je n'ai vu que récemment l'onglet **Lots fiscaux**. Dans les versions antérieures je ne me rappelle pas l'avoir vu. 
![Lots_Fiscaux](https://user-images.githubusercontent.com/93732926/217610904-d7c39b94-59d0-4663-8970-b10d0dab9cb3.png)
Donc correctement paramétré les Charges locatives  et les résultats statistiques affichent désormais des valeurs cohérentes.
Cela peut vous sembler évident mais ce n'était pas du tout intuitif (aide en ligne?).
Ce n'est pas une critique car on est dans le monde du logiciel libre et j'imagine que vous codez sur votre temps libre. En tout cas merci pour cet outil.
Vous pouvez clore cet "issue"

**Comment by bv74** [comment]
Bonjour, 
de mon coté, avec la dernière release, les lots fiscaux restent vides...
Les biens enfants sont bien rattachés au biens parents. d'où cela peut-il venir ? 
Cdlt.

**Comment by Darkjeff** [comment]
va sur la fiche de ton immeuble ou ta maison et clic sur le bouton lot fiscal
tu devrais le voir apparaître dans lots fiscaux 

![image](https://user-images.githubusercontent.com/1095260/217811848-f0cf48f0-aa26-4aea-a97f-2465470e0c6b.png)

**Comment by mikewiza** [comment]
Je ne sais pas si c'est le fonctionnement normal mais pour ma part j'ai du créer les lots fiscaux. Il n'y a rien d'automatique.
1 pour chaque immeuble
1 pour chaque appartement
