### ISSUE TITLE
Feature Request: Ajout d'une colonne type de compteur

### ISSUE THREAD

**Issue by mikygee** [Darkjeff/ultimateimmo#86]
Olivier m'a indiqué que les compteurs pouvaient être utilisés pour les relevés de compteurs d'eau.

Cependant à partir du moment où l'on a plusieurs types de compteurs eau, gaz, électricité on ne peut plus les distinguer.
![image](https://user-images.githubusercontent.com/2222550/185468553-44402538-aba7-4192-a319-7aeac5683125.png)

L'idée serait d'ajouter une nouvelle colonne afin de préciser à quoi se réfère le compteur.
Il faudra aussi que les sommes de compteurs s’additionnent par type.

**Comment by Darkjeff** [comment]
it's working ^^

![image](https://user-images.githubusercontent.com/1095260/185939172-a5800e81-3cac-4a6e-a8e6-ffa34b54e327.png)

**Comment by mikygee** [comment]
Merci,
J'ai l'impression qu'il manque la fiche pour créer les types de compteurs. Je ne trouve pas le fichier immocompteur_type_card.php
A l'heure actuelle impossible de rajouter un nouveau type de compteur..
