### ISSUE TITLE
Bug: Edition d'un lot fiscal > Evennement genere une erreur SQL

### ISSUE THREAD

**Issue by mikygee** [Darkjeff/ultimateimmo#94]
J'ai pu contourner le probleme en executant les requetes suivantes.
ALTER TABLE llx_ultimateimmo_building add date_creation datetime NOT NULL after fk_property;
ALTER TABLE llx_ultimateimmo_building add tms timestamp NOT NULL after date_creation;
ALTER TABLE llx_ultimateimmo_building add fk_user_creat integer NOT NULL after tms;
ALTER TABLE llx_ultimateimmo_building add fk_user_modif integer after fk_user_creat;

**Comment by Darkjeff** [comment]
j'ai ajouté les requetes dans l'update.sql
